paths:
  /api/products:
    get:
      summary: Obtener todos los productos de la BD
      tags: 
        - Productos
      responses:
        "200":
          description: Si la consulta de productos es satisfactoria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsResponse'
        "500":
          description: Si hubo un error en el momento de la consulta

  /api/products/nuevoProducto:
    post:
      summary: Crear un nuevo producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        "200":
          description: Producto creado correctamente
        "400":
          description: Formato de cuerpo inválido
        "500":
          description: Error interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtener un producto por su ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a obtener
          schema:
            type: string
      responses:
        "200":
          description: Producto obtenido exitosamente por ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        "404":
          description: Producto con el ID proporcionado no encontrado
        "500":
          description: Error interno del servidor

    put:
      summary: Actualizar un producto por su ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProduct'
      responses:
        "200":
          description: Producto actualizado exitosamente por ID
        "400":
          description: Formato de cuerpo inválido.
        "404":
          description: Producto con el ID proporcionado no encontrado
        "500":
          description: Error interno del servidor

    delete:
      summary: Eliminar un producto por su ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a eliminar
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado exitosamente por ID
        "404":
          description: Producto con el ID proporcionado no encontrado
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Autogenerated MongoDB ID
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: detalle del producto
        price:
          type: number
          description: precio del producto
      example:
        _id: ObjectId(123abc456efg)
        title: manzana
        description: manzana por kilo
        price: 200

    ProductsResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
          description: Respuesta del estado de los productos
        payload:
          type: array
          description: Lista de productos
          items:
            $ref: '#/components/schemas/Product'

    NewProduct:
      type: object
      properties:
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: detalle del producto
        price:
          type: number
          description: precio del producto
      example:
        title: manzana
        description: manzana por kilo
        price: 200

    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: detalle del producto
        price:
          type: number
          description: precio del producto
      example:
        title: manzana actualizada
        description: manzana por kilo
        price: 250

    ProductResponse:
      type: object
      properties:
        status:
          type: string
          enum: [success, error]
          description: Respuesta del estado del producto
        payload:
          $ref: '#/components/schemas/Product'


