const EErrors = {
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
    INVALID_QUANTITY: "INVALID_QUANTITY",
    CART_NOT_FOUND: "CART_NOT_FOUND",
  };
  
  export default EErrors;